/**
 * @name EAL_LoggerConstants.cls
 * @description common constants for EAL_Logger
 */
public without sharing class EAL_LoggerConstants {
  public static final String FIELD_RECORD_TYPE_ID = 'RecordTypeId';
  public static final String LOGGER_DEFAULT = 'Default';
  public static final String SYMBOL_CLS = '.cls';
  public static final String SYMBOL_DIVIDER = EAL_CommonConstants.SYMBOL_DIVIDER;
  public static final String SYMBOL_NEWLINE = EAL_CommonConstants.SYMBOL_NEWLINE;
}
